### ISSUE TITLE
Please configure your access credentials first

### ISSUE THREAD

**Issue by dev22419** [textmagic/textmagic-rest-bash#1]
Any solution ?

**Comment by dmitry-textmagic** [comment]
Hello @dev22419 

Please configure your credentials by editing "tm.sh" file. You need to put your username in the USERNAME variable and your APIv2 key in the TOKEN, for example:

`readonly USERNAME="charlesconway"`
`readonly TOKEN="abc1235678" `

If you haven't created API keys yet, please proceed to the APIv2 Settings page and create the APIv2 key first: https://my.textmagic.com/online/api/rest-api/keys

**Comment by dev22419** [comment]
Thanks dude
Thank you so much for your help
